version = "1.0"

[main]
name.en = "Send configuration"
name.fr = "Configuration de Send"
services = ["__APP__"]

    [main.config]
    name.en = "Configuration Options"
    name.fr = "Options de configuration"

        [main.config.max_file_size]
        ask.en = "Max File Size"
        ask.fr = "Taille maximale du fichier"
        type = "number"
        default = "2684354560"
        help.en = "Define the maximum file size limit"
        help.fr = "Définir la limite de taille maximale du fichier"
        bind = ":__INSTALL_DIR__/server/config.js"

        [main.config.max_download]
        ask.en = "Max download"
        ask.fr = "Téléchargement maximal"
        type = "number"
        default = "100"
        help.en = "Define the maximum download limit"
        help.fr = "Définir la limite maximale du nombre de téléchargement"
        bind = ":__INSTALL_DIR__/server/config.js"

        [main.config.custom_title]
        ask.en = "Custom Title"
        ask.fr = "Titre personnalisé"
        type = "string"
        help = "Add a custom title for Send"
        bind = ":__INSTALL_DIR__/server/config.js"

        [main.config.custom_description]
        ask.en = "Custom Description"
        ask.fr = "Description personnalisée"
        type = "string"
        help = "Add a custom description for Send"
        bind = ":__INSTALL_DIR__/server/config.js"
